//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prizenew
    {
        public Nullable<int> year { get; set; }
        public string category { get; set; }
        public int? id { get; set; }
        public string firstname { get; set; }
        public string surname { get; set; }
        public string motivation { get; set; }
        public Nullable<int> share { get; set; }
        public string overallMotivation { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    }
}
